# This crate is in its own workspace because of the `blake3` feature that we don't want enabled
# everywhere.
[workspace]
[package]
name = "fibonacci-blake3-test"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../../crates/zkvm/entrypoint", features = ["blake3"]}
